name: flutter_analyze_and_test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: login_form_sample test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: cd login_form_sample/flutter_app && flutter pub get
      # - run: flutter analyze
      - run: cd login_form_sample/flutter_app && flutter test --no-sound-null-safety --coverage
      - uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: $pwd/login_form_sample/flutter_app/coverage/lcov.info